sudo: required
services:
  - docker


before_install:
  - docker build -t AMinenko/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true AMinenko/docker-react npm run test -- --coverage
